This notebook just contains some exploration of the dataset.

In [1]:
import sys

# Necessary to import from src dir
sys.path.append('..')

In [2]:
import matplotlib.pyplot as mlp
import numpy as np
import os
import pandas as pd

from sklearn.preprocessing import StandardScaler

from src.preprocessing import (
    prepare_standardized_datasets,
    standardize_data
)

In [3]:
# Note: notebooks/data is ignored by git, so any files in there will not end up in version control
DATA_DIR = r"./data/"
OUTPUT_DIR = r"./output/"
TEMP_OUTPUT_DIR = r"./temp/"

TRAIN_DATA = os.path.join(DATA_DIR, "train.csv")
TEST_DATA = os.path.join(DATA_DIR, "test.csv")

# Preprocessing

df_train = pd.read_csv(TRAIN_DATA)
df_test = pd.read_csv(TEST_DATA)

label_var = "class4"

# Include only the real-valued mean values, but don't exclude anything further than that yet before exploring the data a bit first
cols_to_include = [feat for feat in df_train.columns.to_list() if (feat.endswith(".mean")) or (feat == label_var)]

numeric_vars = cols_to_include[:]
numeric_vars.remove(label_var)

In [4]:
# Check the Pearson correlation coefficients for the data
# Maybe we can eliminate some redundant variables already at this point

corr = df_train[cols_to_include].corr(numeric_only=True)
corr

,CO2168.mean,CO2336.mean,CO242.mean,CO2504.mean,Glob.mean,H2O168.mean,H2O336.mean,H2O42.mean,H2O504.mean,H2O672.mean,...,SO2168.mean,SWS.mean,T168.mean,T42.mean,T504.mean,T672.mean,T84.mean,UV_A.mean,UV_B.mean,CS.mean
CO2168.mean,1.000000,0.999675,0.993428,0.998567,-0.422862,-0.428546,-0.424609,-0.434061,-0.423042,-0.421750,...,0.313204,-0.144759,-0.565241,-0.563994,-0.568525,-0.567936,-0.564454,-0.434419,-0.434426,-0.106144
CO2336.mean,0.999675,1.000000,0.992175,0.999533,-0.418366,-0.434089,-0.430156,-0.439643,-0.428607,-0.427356,...,0.310494,-0.140993,-0.565057,-0.563768,-0.568681,-0.568213,-0.564217,-0.429937,-0.430238,-0.110800
CO242.mean,0.993428,0.992175,1.000000,0.989651,-0.410648,-0.371312,-0.367937,-0.375666,-0.366559,-0.365313,...,0.316664,-0.157891,-0.523636,-0.523111,-0.526157,-0.525160,-0.523352,-0.416266,-0.406660,-0.082900
CO2504.mean,0.998567,0.999533,0.989651,1.000000,-0.415815,-0.441403,-0.437480,-0.447008,-0.435965,-0.434780,...,0.305035,-0.138026,-0.565800,-0.564382,-0.569942,-0.569724,-0.564860,-0.427277,-0.428167,-0.118085
Glob.mean,-0.422862,-0.418366,-0.410648,-0.415815,1.000000,0.162005,0.156354,0.172892,0.152518,0.151024,...,-0.115704,0.369409,0.594203,0.592415,0.589929,0.589997,0.596149,0.985450,0.935493,0.122259
H2O168.mean,-0.428546,-0.434089,-0.371312,-0.441403,0.162005,1.000000,0.999883,0.999604,0.999704,0.999495,...,-0.242150,-0.239006,0.815735,0.816751,0.820090,0.821259,0.814638,0.252725,0.371318,0.476726
H2O336.mean,-0.424609,-0.430156,-0.367937,-0.437480,0.156354,0.999883,1.000000,0.999138,0.999937,0.999789,...,-0.241652,-0.241590,0.812800,0.813907,0.817181,0.818372,0.811749,0.246731,0.365475,0.478715
H2O42.mean,-0.434061,-0.439643,-0.375666,-0.447008,0.172892,0.999604,0.999138,1.000000,0.998759,0.998440,...,-0.243284,-0.235336,0.820766,0.821548,0.825134,0.826284,0.819552,0.263820,0.382417,0.472611
H2O504.mean,-0.423042,-0.428607,-0.366559,-0.435965,0.152518,0.999704,0.999937,0.998759,1.000000,0.999901,...,-0.241047,-0.242402,0.810517,0.811649,0.814972,0.816216,0.809472,0.242609,0.361413,0.479612
H2O672.mean,-0.421750,-0.427356,-0.365313,-0.434780,0.151024,0.999495,0.999789,0.998440,0.999901,1.000000,...,-0.239400,-0.243683,0.808509,0.809640,0.813044,0.814364,0.807462,0.240687,0.359400,0.480559
H2O84.mean,-0.430685,-0.436302,-0.372606,-0.443697,0.167678,0.999819,0.999468,0.999923,0.999156,0.998878,...,-0.242413,-0.237727,0.818248,0.819104,0.822627,0.823792,0.817062,0.258585,0.377290,0.474163
NET.mean,-0.422650,-0.418452,-0.404371,-0.415830,0.958582,0.259704,0.253878,0.270776,0.249745,0.247545,...,-0.152259,0.317065,0.678276,0.677598,0.673098,0.672476,0.680521,0.968309,0.944963,0.164280
NO168.mean,0.313527,0.313772,0.310697,0.311764,-0.202775,-0.179052,-0.177031,-0.181699,-0.174771,-0.176285,...,0.356508,-0.005719,-0.275227,-0.275803,-0.274379,-0.273761,-0.275865,-0.221350,-0.224884,0.079420
NO336.mean,0.315999,0.316393,0.313074,0.314534,-0.205669,-0.180530,-0.178494,-0.183216,-0.176259,-0.177750,...,0.368986,-0.006420,-0.279556,-0.280132,-0.278866,-0.278337,-0.280195,-0.224127,-0.228365,0.086300
NO42.mean,0.280128,0.280200,0.281742,0.278196,-0.184535,-0.124370,-0.122643,-0.126422,-0.120540,-0.122613,...,0.294757,-0.019264,-0.212770,-0.213338,-0.211937,-0.211479,-0.213451,-0.196217,-0.190294,0.065363
NO504.mean,0.316320,0.316849,0.313449,0.315260,-0.204867,-0.175997,-0.173983,-0.178681,-0.171791,-0.173371,...,0.366177,-0.009023,-0.274471,-0.274964,-0.274073,-0.273748,-0.275071,-0.222353,-0.225951,0.086779
NO672.mean,0.316230,0.316829,0.313297,0.315419,-0.207654,-0.172522,-0.170472,-0.175280,-0.168280,-0.169935,...,0.363430,-0.011376,-0.271803,-0.272199,-0.271580,-0.271422,-0.272355,-0.224312,-0.227045,0.086162
NO84.mean,0.296894,0.297107,0.295187,0.295235,-0.196577,-0.164550,-0.162625,-0.166982,-0.160387,-0.162199,...,0.326332,-0.007320,-0.253410,-0.253946,-0.252620,-0.252139,-0.254025,-0.213773,-0.215496,0.068217
NOx168.mean,0.333475,0.331076,0.320408,0.327457,-0.379017,-0.247758,-0.244600,-0.253382,-0.242232,-0.241700,...,0.545796,-0.023476,-0.419060,-0.418967,-0.416569,-0.415578,-0.419698,-0.404022,-0.412949,0.258020
NOx336.mean,0.327993,0.325752,0.314951,0.322334,-0.378293,-0.241915,-0.238752,-0.247569,-0.236401,-0.235932,...,0.542446,-0.025501,-0.412878,-0.412726,-0.410603,-0.409772,-0.413485,-0.402830,-0.411658,0.261331
NOx42.mean,0.336236,0.333769,0.323275,0.330030,-0.378163,-0.248760,-0.245627,-0.254346,-0.243270,-0.242703,...,0.544725,-0.024247,-0.419947,-0.419919,-0.417297,-0.416222,-0.420616,-0.403102,-0.411409,0.254124
NOx504.mean,0.328314,0.326264,0.315583,0.323180,-0.378428,-0.234539,-0.231412,-0.240180,-0.229117,-0.228762,...,0.539651,-0.029257,-0.406100,-0.405863,-0.404167,-0.403558,-0.406675,-0.401654,-0.409096,0.263986
NOx672.mean,0.326896,0.324950,0.314258,0.322097,-0.377987,-0.232071,-0.228968,-0.237657,-0.226715,-0.226452,...,0.535500,-0.030722,-0.401768,-0.401506,-0.400017,-0.399605,-0.402318,-0.400479,-0.407938,0.261715
NOx84.mean,0.333180,0.330769,0.319901,0.327141,-0.377054,-0.251107,-0.247969,-0.256701,-0.245607,-0.245056,...,0.547322,-0.021350,-0.421235,-0.421174,-0.418703,-0.417689,-0.421880,-0.402448,-0.411792,0.255240
O3168.mean,-0.265492,-0.263782,-0.279265,-0.262092,0.637383,-0.003638,-0.006366,0.000514,-0.008143,-0.007949,...,0.018293,0.233383,0.316594,0.317915,0.312280,0.311258,0.319826,0.627352,0.524432,0.236192
O342.mean,-0.229594,-0.227116,-0.251528,-0.224246,0.610403,-0.062976,-0.064956,-0.060340,-0.066377,-0.066040,...,0.029605,0.239547,0.261876,0.264023,0.256639,0.255224,0.265672,0.594966,0.484682,0.211656
O3504.mean,-0.289319,-0.288780,-0.297963,-0.288744,0.645860,0.042942,0.039852,0.047646,0.037918,0.038085,...,0.011738,0.220549,0.351259,0.352139,0.348270,0.347907,0.354143,0.639325,0.542674,0.257663
O3672.mean,-0.291102,-0.290778,-0.298367,-0.291150,0.646939,0.056107,0.052931,0.060831,0.050914,0.051078,...,0.008147,0.216516,0.361582,0.362351,0.358784,0.358643,0.364367,0.641393,0.546956,0.263950
O384.mean,-0.249776,-0.247571,-0.268259,-0.245188,0.624063,-0.039008,-0.041285,-0.035700,-0.042823,-0.042520,...,0.023613,0.238995,0.285615,0.287320,0.280870,0.279656,0.289143,0.610246,0.502857,0.221986
Pamb0.mean,-0.055435,-0.056018,-0.044682,-0.058284,0.335392,-0.025448,-0.026691,-0.022215,-0.027475,-0.027605,...,0.038240,0.255821,0.142641,0.139197,0.144317,0.146571,0.142673,0.302151,0.302643,0.162627
PAR.mean,-0.416232,-0.411498,-0.401853,-0.408535,0.995727,0.196813,0.191032,0.207756,0.187030,0.185279,...,-0.128520,0.355414,0.628545,0.626943,0.623711,0.623563,0.630505,0.993120,0.951705,0.130481
PTG.mean,0.085736,0.075425,0.101661,0.058404,-0.241924,-0.087405,-0.085759,-0.088621,-0.082395,-0.078353,...,0.187037,-0.030963,-0.279860,-0.287394,-0.256129,-0.238776,-0.285174,-0.275335,-0.251205,0.020351
RGlob.mean,-0.255459,-0.251949,-0.248184,-0.251465,0.841892,-0.059047,-0.063758,-0.050213,-0.066642,-0.066435,...,0.109747,0.414229,0.274162,0.270773,0.271954,0.273582,0.275413,0.797646,0.699350,0.075690
RHIRGA168.mean,0.386704,0.381320,0.384169,0.376457,-0.906972,-0.072952,-0.067677,-0.082931,-0.063809,-0.061697,...,0.182154,-0.380551,-0.592716,-0.590443,-0.587098,-0.585989,-0.594155,-0.897537,-0.851695,-0.086936
RHIRGA336.mean,0.406161,0.401020,0.401864,0.396393,-0.907548,-0.093374,-0.087760,-0.103784,-0.083754,-0.081531,...,0.191893,-0.373386,-0.609244,-0.606817,-0.603958,-0.602848,-0.610527,-0.900208,-0.857056,-0.090951
RHIRGA42.mean,0.371392,0.365868,0.372490,0.360808,-0.904034,-0.050634,-0.045948,-0.059238,-0.042406,-0.040522,...,0.168652,-0.391653,-0.572434,-0.571036,-0.566511,-0.565363,-0.574449,-0.892708,-0.842045,-0.091357
RHIRGA504.mean,0.406581,0.401716,0.401501,0.397559,-0.906782,-0.094925,-0.089227,-0.105527,-0.085106,-0.082901,...,0.191858,-0.369739,-0.609199,-0.606555,-0.604472,-0.603657,-0.610341,-0.899398,-0.857659,-0.091190
RHIRGA672.mean,0.404303,0.399538,0.398692,0.395602,-0.904156,-0.095872,-0.090149,-0.106555,-0.086037,-0.083590,...,0.193015,-0.370665,-0.608773,-0.605979,-0.604503,-0.604303,-0.609804,-0.897188,-0.857215,-0.091321
RHIRGA84.mean,0.376076,0.370525,0.375997,0.365472,-0.906807,-0.054959,-0.050074,-0.064102,-0.046422,-0.044462,...,0.171328,-0.390618,-0.576628,-0.574869,-0.570779,-0.569631,-0.578470,-0.895416,-0.845685,-0.087847
RPAR.mean,0.071932,0.073515,0.066367,0.072817,0.438492,-0.316262,-0.318044,-0.312841,-0.318896,-0.316850,...,0.351267,0.332946,-0.172519,-0.174974,-0.174468,-0.172611,-0.171180,0.384020,0.251877,0.026160
SO2168.mean,0.313204,0.310494,0.316664,0.305035,-0.115704,-0.242150,-0.241652,-0.243284,-0.241047,-0.239400,...,1.000000,0.106882,-0.382859,-0.383947,-0.381384,-0.378936,-0.382973,-0.141099,-0.177995,0.390353
SWS.mean,-0.144759,-0.140993,-0.157891,-0.138026,0.369409,-0.239006,-0.241590,-0.235336,-0.242402,-0.243683,...,0.106882,1.000000,-0.016481,-0.017794,-0.019080,-0.018587,-0.015420,0.333627,0.268503,-0.010070
T168.mean,-0.565241,-0.565057,-0.523636,-0.565800,0.594203,0.815735,0.812800,0.820766,0.810517,0.808509,...,-0.382859,-0.016481,1.000000,0.999808,0.999657,0.999087,0.999921,0.664180,0.745461,0.392475
T42.mean,-0.563994,-0.563768,-0.523111,-0.564382,0.592415,0.816751,0.813907,0.821548,0.811649,0.809640,...,-0.383947,-0.017794,0.999808,1.000000,0.999254,0.998550,0.999945,0.663234,0.744011,0.393383
T504.mean,-0.568525,-0.568681,-0.526157,-0.569942,0.589929,0.820090,0.817181,0.825134,0.814972,0.813044,...,-0.381384,-0.019080,0.999657,0.999254,1.000000,0.999802,0.999422,0.659500,0.742149,0.395626
T672.mean,-0.567936,-0.568213,-0.525160,-0.569724,0.589997,0.821259,0.818372,0.826284,0.816216,0.814364,...,-0.378936,-0.018587,0.999087,0.998550,0.999802,1.000000,0.998765,0.659218,0.742560,0.397936
T84.mean,-0.564454,-0.564217,-0.523352,-0.564860,0.596149,0.814638,0.811749,0.819552,0.809472,0.807462,...,-0.382973,-0.015420,0.999921,0.999945,0.999422,0.998765,1.000000,0.666278,0.746724,0.392643
UV_A.mean,-0.434419,-0.429937,-0.416266,-0.427277,0.985450,0.252725,0.246731,0.263820,0.242609,0.240687,...,-0.141099,0.333627,0.664180,0.663234,0.659500,0.659218,0.666278,1.000000,0.964597,0.143262
UV_B.mean,-0.434426,-0.430238,-0.406660,-0.428167,0.935493,0.371318,0.365475,0.382417,0.361413,0.359400,...,-0.177995,0.268503,0.745461,0.744011,0.742149,0.742560,0.746724,0.964597,1.000000,0.185061
CS.mean,-0.106144,-0.110800,-0.082900,-0.118085,0.122259,0.476726,0.478715,0.472611,0.479612,0.480559,...,0.390353,-0.010070,0.392475,0.393383,0.395626,0.397936,0.392643,0.143262,0.185061,1.000000

In [5]:
def get_n_largest_pearson_coeffs_for_variable(
    corr,
    variable,
    n=10
):
    return np.abs(corr[variable]).nlargest(n)

In [6]:
# We can get the indices of the variables with which the correlation is largest
get_n_largest_pearson_coeffs_for_variable(corr, "CO2168.mean").index

Index(['CO2168.mean', 'CO2336.mean', 'CO2504.mean', 'CO242.mean', 'T504.mean',
       'T672.mean', 'T168.mean', 'T84.mean', 'T42.mean', 'UV_B.mean'],
      dtype='object')

In [7]:
# Or just view the values
get_n_largest_pearson_coeffs_for_variable(corr, "CO2168.mean")

CO2168.mean    1.000000
CO2336.mean    0.999675
CO2504.mean    0.998567
CO242.mean     0.993428
T504.mean      0.568525
T672.mean      0.567936
T168.mean      0.565241
T84.mean       0.564454
T42.mean       0.563994
UV_B.mean      0.434426
Name: CO2168.mean, dtype: float64

Looking at the covariances, we notice very quickly that for $CO_2$ values, it's probably enough to include just one.

In [8]:
# Figure out the columns with the highest overall correlation coefficients
# by calculating the sum of the absolute value of the correlation coefficient table
# and sorting to find those that might be most correlated with others.

n_pearsons_sum_per_col = []

for col in corr.columns:
    n_pearsons_sum_per_col.append(get_n_largest_pearson_coeffs_for_variable(corr, col, len(corr.columns)).sum())

exploratory_table = corr.copy()
exploratory_table["sum_pearson"] = n_pearsons_sum_per_col

exploratory_table["sum_pearson"].nlargest(50)

T84.mean          26.307055
T168.mean         26.270590
T42.mean          26.267059
T504.mean         26.200806
T672.mean         26.170127
UV_B.mean         26.060934
UV_A.mean         26.026486
NET.mean          25.596835
PAR.mean          25.451764
Glob.mean         25.005143
RHIRGA336.mean    24.933839
RHIRGA504.mean    24.930007
RHIRGA672.mean    24.814426
RHIRGA168.mean    24.595503
RHIRGA84.mean     24.303401
RHIRGA42.mean     24.212245
NOx42.mean        22.681271
NOx84.mean        22.673173
NOx168.mean       22.673092
NOx336.mean       22.570084
NOx504.mean       22.499140
NOx672.mean       22.411238
O3672.mean        21.114269
O3504.mean        20.941694
O3168.mean        20.288422
CO2168.mean       20.049462
O384.mean         20.004236
CO2336.mean       19.996899
CO2504.mean       19.946889
O342.mean         19.699757
CO242.mean        19.340127
NO336.mean        19.226499
NO504.mean        19.158918
NO672.mean        19.124453
NO168.mean        19.054896
NO84.mean         18.403734
RGlob.mean        17.820958
H2O42.mean        17.757593
H2O84.mean        17.671729
H2O168.mean       17.571500
H2O336.mean       17.460885
NO42.mean         17.456256
H2O504.mean       17.375320
H2O672.mean       17.338674
SO2168.mean       14.026471
RPAR.mean         12.538041
CS.mean           11.440678
SWS.mean           9.542986
PTG.mean           8.909189
Pamb0.mean         7.466784
Name: sum_pearson, dtype: float64

In [9]:
# If nothing else, we at least may want to keep the variables towards the low end for a longer while

In [10]:
# Prepare standardized datasets

df_train, df_validation, df_test = prepare_standardized_datasets(
    df_train=df_train,
    df_test=df_test,
    data_vars=numeric_vars,
    label_var=label_var,
    label_values=("nonevent", "event"),
    include_validation_split=True,
    validation_split_size=0.2
)

In [14]:
df_train, _, df_test = prepare_standardized_datasets(
    df_train=df_train,
    df_test=df_test,
    data_vars=numeric_vars,
    label_var=label_var,
    label_values=("nonevent", "event"),
    include_validation_split=False,
    validation_split_size=0.2
)

In [15]:
df_train.head()

,class4,CO2168.mean,CO2336.mean,CO242.mean,CO2504.mean,Glob.mean,H2O168.mean,H2O336.mean,H2O42.mean,H2O504.mean,...,SO2168.mean,SWS.mean,T168.mean,T42.mean,T504.mean,T672.mean,T84.mean,UV_A.mean,UV_B.mean,CS.mean
0,event,-0.843284,-0.806178,-0.749904,-0.779346,0.851016,-0.381931,-0.390005,-0.326875,-0.395056,...,-0.535031,0.414331,0.258275,0.195343,0.243301,0.242919,0.220021,0.463568,0.404275,-0.690468
1,event,-0.909258,-0.901013,-0.957330,-0.885940,-0.678721,0.995845,1.003319,0.971381,1.010501,...,-0.588183,0.344518,0.530734,0.542361,0.525037,0.525596,0.532190,-0.447675,-0.221725,0.121596
2,event,-0.788545,-0.858080,-0.718858,-0.954125,-0.996964,0.675420,0.679352,0.669455,0.677365,...,-0.600890,-0.550207,0.217902,0.244002,0.223605,0.233052,0.216188,-0.891703,-0.884774,-0.669991
3,event,-1.450075,-1.437434,-1.546171,-1.424263,0.684215,0.073630,0.071292,0.095712,0.071972,...,0.651056,0.433459,0.521701,0.486989,0.544710,0.539018,0.518784,0.220481,0.423714,1.283602
4,event,0.002070,0.019693,0.086694,0.034396,0.847362,1.982168,1.997591,1.953313,2.005163,...,0.289840,0.264095,1.550111,1.558378,1.539554,1.540126,1.556622,0.903245,1.467806,1.667170

In [16]:
df_test.head()

,CO2168.mean,CO2336.mean,CO242.mean,CO2504.mean,Glob.mean,H2O168.mean,H2O336.mean,H2O42.mean,H2O504.mean,H2O672.mean,...,SO2168.mean,SWS.mean,T168.mean,T42.mean,T504.mean,T672.mean,T84.mean,UV_A.mean,UV_B.mean,CS.mean
0,-1.118472,-1.132191,-1.158624,-1.130211,1.200503,1.351899,1.353238,1.339886,1.357780,1.360061,...,-0.472452,0.381289,1.326148,1.339288,1.320454,1.323639,1.330858,1.379542,1.634996,0.376366
1,-0.973844,-0.952001,-1.057652,-0.937878,1.352984,-0.461841,-0.466771,-0.452994,-0.466866,-0.466333,...,-0.399677,0.410935,0.637692,0.630600,0.640245,0.650919,0.640302,1.143024,0.992869,1.253726
2,0.697000,0.697619,0.687074,0.696291,-1.141205,-0.851818,-0.836964,-0.864219,-0.845616,-0.830904,...,2.810646,0.102848,-1.189380,-1.171034,-1.195394,-1.201929,-1.177207,-1.057774,-1.128053,1.919376
3,1.345761,1.347395,1.317112,1.346704,0.183713,-1.171722,-1.177013,-1.161082,-1.179224,-1.124627,...,-0.316036,0.298544,-1.568541,-1.575249,-1.587386,-1.600795,-1.566562,0.051622,-0.525677,-0.939134
4,-1.020092,-1.004697,-1.009901,-1.004807,0.813245,0.426985,0.418221,0.438750,0.413230,0.411642,...,-0.445689,0.610007,0.728378,0.719375,0.730776,0.732718,0.718298,1.115702,0.966431,-0.472808