In [1]:
# This notebook is just to have a clean version/demos of functions in preprocessing.py

In [2]:
import sys

# Necessary to import from src dir
sys.path.append('..')

In [3]:
import numpy as np
import os
import pandas as pd

from src.preprocessing import prepare_standardized_datasets

In [4]:
# Note: notebooks/data is ignored by git, so any files in there will not end up in version control
DATA_DIR = r"./data/"
OUTPUT_DIR = r"./output/"
TEMP_OUTPUT_DIR = r"./temp/"

TRAIN_DATA = os.path.join(DATA_DIR, "train.csv")
TEST_DATA = os.path.join(DATA_DIR, "test.csv")

# Preprocessing

df_train = pd.read_csv(TRAIN_DATA)
df_test = pd.read_csv(TEST_DATA)

label_var = "class4"

# Include only the real-valued mean values, but don't exclude anything further than that yet before exploring the data a bit first
cols_to_include = [feat for feat in df_train.columns.to_list() if (feat.endswith(".mean")) or (feat == label_var)]

numeric_vars = cols_to_include[:]
numeric_vars.remove(label_var)

In [14]:
# Prepare standardized datasets

# Under the hood, the training data is first split into training and 
# validation datasets, after which the data is standardized.

# For standardization, a scaler is fit on the training data, and the same 
# scaler is used to transform the validation and testing data.

df_train, df_validation, df_test = prepare_standardized_datasets(
    df_train=df_train,
    df_test=df_test,
    data_vars=numeric_vars,
    label_var=label_var,
    label_values=("nonevent", "event"),
    include_validation_split=True,
    validation_split_size=0.2
)

# To create standardized datasets without a validation split, simply
# call prepare_standardized_datasets() with include_validation_split=False.
# The df_validation in the resulting tuple will be None.

In [15]:
df_train.head()

,class4,CO2168.mean,CO2336.mean,CO242.mean,CO2504.mean,Glob.mean,H2O168.mean,H2O336.mean,H2O42.mean,H2O504.mean,...,SO2168.mean,SWS.mean,T168.mean,T42.mean,T504.mean,T672.mean,T84.mean,UV_A.mean,UV_B.mean,CS.mean
0,event,-0.021076,-0.033515,-0.076087,-0.028607,-1.216845,-0.671422,-0.671189,-0.682914,-0.671542,...,-0.538355,0.617709,-0.944188,-0.927150,-0.950700,-0.950049,-0.935096,-1.169257,-1.167082,-0.272673
1,event,0.228276,0.221477,0.183267,0.214032,0.199360,-0.767690,-0.758731,-0.787928,-0.745702,...,0.484255,0.699433,-0.846540,-0.839376,-0.860948,-0.817189,-0.833162,0.060876,-0.637219,-0.198478
2,event,1.159845,1.165085,1.100416,1.168434,0.321916,-1.016056,-1.010615,-1.022068,-1.009047,...,-0.498520,0.368830,-0.950637,-0.939865,-0.980299,-0.993560,-0.937747,0.336267,-0.118095,-0.983023
3,event,1.339944,1.341243,1.276660,1.340009,-1.240688,-1.213391,-1.206352,-1.226267,-1.201084,...,-0.144540,0.179807,-1.794666,-1.811488,-1.767378,-1.745502,-1.806886,-1.308256,-1.254037,-0.796510
4,event,1.154627,1.159003,1.117701,1.165802,0.549081,-1.140802,-1.139479,-1.141468,-1.138711,...,-0.365377,0.326735,-0.903665,-0.897924,-0.933564,-0.947453,-0.891114,0.415484,-0.167717,-0.801709

In [16]:
df_validation.head()

,class4,CO2168.mean,CO2336.mean,CO242.mean,CO2504.mean,Glob.mean,H2O168.mean,H2O336.mean,H2O42.mean,H2O504.mean,...,SO2168.mean,SWS.mean,T168.mean,T42.mean,T504.mean,T672.mean,T84.mean,UV_A.mean,UV_B.mean,CS.mean
0,event,1.445218,1.445800,1.442672,1.445306,-1.317899,0.227976,0.229698,0.212627,0.237391,...,-0.516063,-1.089424,-0.101975,-0.102399,-0.101064,-0.107746,-0.109314,-1.319117,-1.143244,0.884764
1,event,-0.348757,-0.347056,-0.399341,-0.352924,1.360430,-0.691990,-0.689732,-0.693162,-0.704028,...,-0.035974,0.737992,0.564529,0.559754,0.577764,0.572024,0.574530,1.186036,0.737294,0.697330
2,event,0.361563,0.365648,0.393592,0.378900,-0.850605,1.475877,1.510661,1.454515,1.536302,...,-0.579999,0.364293,0.642104,0.653362,0.635231,0.636681,0.642703,-0.716865,-0.388839,0.352994
3,event,-0.535877,-0.544335,-0.557583,-0.545598,0.070911,0.123700,0.090297,0.154463,0.062818,...,-0.334323,-1.121916,0.242732,0.241071,0.248956,0.262046,0.242955,0.275635,0.063314,-0.403492
4,event,-0.778675,-0.768462,-0.715413,-0.744825,0.337523,1.705369,1.711705,1.694132,1.712999,...,-0.429971,0.279795,1.025579,1.019108,1.028536,1.026011,1.020754,0.601833,0.814181,-0.169176

In [17]:
df_test.head()

,CO2168.mean,CO2336.mean,CO242.mean,CO2504.mean,Glob.mean,H2O168.mean,H2O336.mean,H2O42.mean,H2O504.mean,H2O672.mean,...,SO2168.mean,SWS.mean,T168.mean,T42.mean,T504.mean,T672.mean,T84.mean,UV_A.mean,UV_B.mean,CS.mean
0,-1.180640,-1.200235,-1.203571,-1.202217,1.221640,1.569129,1.570953,1.560999,1.575342,1.577832,...,-0.436153,0.384940,1.441190,1.453251,1.435086,1.435093,1.445133,1.401471,1.685033,0.545968
1,-1.029829,-1.011822,-1.099128,-1.000735,1.374904,-0.420183,-0.425763,-0.409272,-0.425858,-0.425007,...,-0.359109,0.416889,0.716994,0.707856,0.720270,0.730340,0.718734,1.163321,1.033134,1.499021
2,0.712455,0.713075,0.705593,0.711172,-1.132094,-0.847910,-0.831898,-0.861186,-0.841256,-0.824799,...,3.039532,0.084868,-1.204928,-1.187092,-1.208760,-1.210740,-1.193114,-1.052658,-1.120062,2.222098
3,1.388955,1.392501,1.357296,1.392525,0.199629,-1.198781,-1.204963,-1.187421,-1.207144,-1.146899,...,-0.270561,0.295767,-1.603773,-1.612243,-1.620696,-1.628600,-1.602678,0.064391,-0.508519,-0.883022
4,-1.078054,-1.066922,-1.049735,-1.070848,0.832393,0.554683,0.545154,0.570703,0.539397,0.537788,...,-0.407820,0.631426,0.812388,0.801230,0.815407,0.816034,0.800778,1.135811,1.006294,-0.376466